


exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


description: Li-Kai (Kevin) Chi's personal website
author:
  name: Li-Kai (Kevin) Chi
  email: kevinjipotw@gmail.com
  github: kevinchipotw
  # twitter: dbtek
  # pinterest: asd123
  linkedin: kevinjipotw
  # email_md5: 726351295ec82e145928582f595aa3aa


# BASE_PATH: 
